services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-backend:
    container_name: perplexica-backend
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
      - mongodb
      - cairobook-ingest
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/perplexica/data
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - perplexica-network
    environment:
      - MONGODB_ATLAS_URI=${MONGODB_ATLAS_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped

  perplexica-frontend:
    container_name: perplexica-frontend
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://backend.chat.starknet.builders/api
        - NEXT_PUBLIC_WS_URL=wss://backend.chat.starknet.builders
    depends_on:
      - perplexica-backend
    ports:
      - 3000:3000
    networks:
      - perplexica-network
    restart: unless-stopped

  mongodb:
    image: mongodb/mongodb-atlas-local
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27018:27017
    networks:
      - perplexica-network
    restart: unless-stopped

  cairobook-ingest:
    build:
      context: .
      dockerfile: ingest.dockerfile
    depends_on:
      - mongodb
    networks:
      - perplexica-network
    environment:
      - MONGODB_ATLAS_URI=${MONGODB_ATLAS_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: 'no'

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: '(backend.)?chat.starknet.builder'
      SITES: 'backend.chat.starknet.builders=perplexica-backend:3001;chat.starknet.builders=perplexica-frontend:3000'
    networks:
      - perplexica-network
    depends_on:
      - perplexica-backend
      - perplexica-frontend

networks:
  perplexica-network:

volumes:
  backend-dbstore:
  mongodb-data:
  ssl_data:
