services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - perplexica-network
    restart: always

  perplexica-backend:
    container_name: perplexica-backend
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://searxng:8080
    depends_on:
      - searxng
    ports:
      - 3001:3001
    volumes:
      - ./src:/home/perplexica/src
      - ./config.toml:/home/perplexica/config.toml
      - backend-dbstore:/home/perplexica/data
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - perplexica-network
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_HOSTED_MODE=true
    restart: always

  perplexica-frontend:
    container_name: perplexica-frontend
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://backend.agent.starknet.builders/api
        - NEXT_PUBLIC_WS_URL=wss://backend.agent.starknet.builders
        - NEXT_PUBLIC_HOSTED_MODE=true
    depends_on:
      - perplexica-backend
    ports:
      - 3000:3000
    networks:
      - perplexica-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: '(backend.)?agent.starknet.builder'
      SITES: 'backend.agent.starknet.builders=perplexica-backend:3001;agent.starknet.builders=perplexica-frontend:3000'
    networks:
      - perplexica-network
    depends_on:
      - perplexica-backend
      - perplexica-frontend

networks:
  perplexica-network:

volumes:
  backend-dbstore:
  ssl_data:
