[API_KEYS]
OPENAI = ""
GROQ = ""
ANTHROPIC = ""

[API_ENDPOINTS]
OLLAMA = ""
SEARXNG = "http://localhost:32768"

[CAIRO_DB]
MONGODB_URI = ""
DB_NAME = ""
COLLECTION_NAME = ""

[STARKNET_DB]
MONGODB_URI = ""
DB_NAME = ""
COLLECTION_NAME = ""

[GENERAL]
PORT = 3_001
SIMILARITY_MEASURE = "cosine"
